### ISSUE TITLE
Scroll position is not reset on page visits

### ISSUE THREAD

**Issue by simon-roland** [inertiajs/inertia#1192]
### Versions:

- `@inertiajs/inertia` version: 0.11.0
- `@inertiajs/inertia-vue3` version: 0.6.0

### Describe the problem:

Scroll position should reset after navigation.

After updating to the latest version of Google Chrome, this is no longer the case.

### Steps to reproduce:

1. Update to the latest Chrome. The issue was observed in version 102.0.5005.63
2. Scroll down from the top of the page
3. Navigate using the Link component or manual visit
4. Scroll position is kept even though preserveScroll is set to false or not set at all

**Comment by LX4777** [comment]
I have the same issue

**Versions:** 
-         @inertiajs/inertia": 0.11.0
-         @inertiajs/inertia-react: 0.8.0

Google Chrome 102.0.5005.78

**Comment by craigrileyuk** [comment]
#1099 addresses this issue. Just waiting for it to be merged into main and released.

**Comment by vpuentem** [comment]
I have the same issue

**Comment by simon-roland** [comment]
I believe the changes that were merged from #1099 will also fix this issue.

Any idea when we will see those changes released?

**Comment by prashant0078** [comment]
Facing the same issue 

my package.json

{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@fortawesome/fontawesome-free": "^6.1.2",
        "@popperjs/core": "^2.10.2",
        "axios": "^0.25",
        "bootstrap": "^4.6.1",
        "jquery": "^1.12.4",
        "jquery.scrollbar": "^0.2.11",
        "laravel-mix": "^6.0.6",
        "laravel-vite-plugin": "^0.4.0",
        "lodash": "^4.17.19",
        "popper.js": "^1.16.1",
        "postcss": "^8.1.14",
        "resolve-url-loader": "^5.0.0",
        "sass": "^1.32.11",
        "sass-loader": "^11.0.1",
        "vite": "^2.9.11",
        "webpack-modernizr-loader": "^5.0.0"
    },
    "dependencies": {
        "@babel/plugin-syntax-dynamic-import": "^7.8.3",
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "@inertiajs/progress": "^0.2.7",
        "vue": "^3.2.31",
        "vue-loader": "^17.0.0"
    }
}

**Comment by MirasMustimov** [comment]
While the PR is not released, I was wondering if it's ok to just subscribe to inertia success event and reset scroll there? Putting this code in my Layout.vue seems to work
@reinink 

```js
Inertia.on('success', (event) => {
    window.scrollTo({ top: 0, left: 0, behavior: 'instant' })
})
```

**Comment by jackkitley** [comment]
> While the PR is not released, I was wondering if it's ok to just subscribe to inertia success event and reset scroll there? Putting this code in my Layout.vue seems to work @reinink
> 
> ```js
> Inertia.on('success', (event) => {
>     window.scrollTo({ top: 0, left: 0, behavior: 'instant' })
> })
> ```

Used this but affected all my links. i guess you could filter it out. I wanted to also scroll to certain sections so i ended up with this

on Page:
`<Link :href="route('lead.validation', lead.id) + '#leadValidation'"
                                ><span class="blue_6">{{ lead.id }}</span></Link
                            >`

in Layout:
`onMounted(() => {
    if (location.hash) $(location.hash).scroll()
})`

**Comment by reinink** [comment]
Hey folks, sorry for the delay on getting this fix out. It's going to be part of the next big release we do to Inertia (see #1282).

**Comment by JackEllis** [comment]
Thanks @reinink. Just running into this. Passing preserveScroll: false with an Inertia.put() and was expecting it to go up to the top (to show success message). Excited for the next release.

**Comment by reinink** [comment]
Hey folks, I just deployed this fix as `@inertiajs/inertia@0.11.0`. It was fixed in #1099.

**Comment by tykatyk** [comment]
Scroll position is still not reset in Firefox 108.0.2 and  `@inertiajs/inertia@0.11.1`

**Comment by benjivm** [comment]
Yep, Firefox scroll is still messed up in Inertia apps.

**Comment by JackEllis** [comment]
@benjivm Are you using Inertia 1.0?

**Comment by benjivm** [comment]
@JackEllis `1.0.11`, I have been relying on this polyfill to get it to behave somewhat normally in Firefox but it has a noticeable visual delay and sometimes messes up: https://github.com/janpaul123/delayed-scroll-restoration-polyfill

**Comment by Thiritin** [comment]
Still messed up in 2025
