### ISSUE TITLE
Error cant find module: import createServer from '@inertiajs/react/server';

### ISSUE THREAD

**Issue by mohammad-hassani** [inertiajs/inertia#1416]
### Version:

- `@inertiajs/react` version: 1.0.0

### Describe the problem:

cant find module when I import createServer from '@inertiajs/react/server';
in ssr.jsx file

### Steps to reproduce:

I'm upgrading Inertia from 0.11.1 to 1.0.0 and using upgrade guide from [official web page](https://inertiajs.com/upgrade-guide)

**Comment by sglass520** [comment]
I'm experiencing the same issue. Although eslint only shows the error when its a tsx file and not jsx, either way it cant find the createServer module from '@inertiajs/react/server'.

**Comment by jessarcher** [comment]
Thanks for reporting! This has been fixed in #1397, which we'll be releasing soon.

**Comment by rockblings** [comment]
Experiencing the same issue, while we wait for the release, is there is workaround?

**Comment by rockblings** [comment]
> > Experiencing the same issue, while we wait for the release, is there is workaround?
> 
> @rockblings you can change the .jsx to .tsx format and it's work fine
> 
> or in bad way you can remove the `"checkJs": true,` from jsconfig.json

Thanks for your response but it is already in .tsx and still cant find the module
