### ISSUE TITLE
Svelte SSR does not render component CSS

### ISSUE THREAD

**Issue by buhrmi** [inertiajs/inertia#1760]
### Version:

- `@inertiajs/svelte` version: 1.0.14

### Describe the problem:

When using Svelte SSR, the server side renderer does not render the component CSS, which results in content shifting around once the CSS is loaded via Javascript.

**Comment by akorajac** [comment]
any update on this? Same problem with laravel/breeze/vue

**Comment by buhrmi** [comment]
there is a PR https://github.com/inertiajs/inertia/pull/1761

**Comment by buhrmi** [comment]
We should start brainstorming how this can be fixed for Svelte 5. Since Svelte 5's `component.render()` call does not return css anymore, we have to find that CSS in other places. One place where we can look is Vite's `manifest.json` file. If we had a list of module IDs that are being used during the `render` call, we could look up all the CSS files in the manifest and include this in the `<head>`. There is an example in the Vite docs how to do this with VueServerRenderer: https://vitejs.dev/guide/ssr#generating-preload-directives
Unfortunately, I can't find a way to get a list of the module IDs with Svelte's render function. I know there must be a way since obviously frameworks exist that support Svelte SSR (SvelteKit, etc.). If anybody can help take a look, would be awesome.

**Comment by buhrmi** [comment]
If anyone is in a position like me and wants to preload the CSS when using SSR with Svelte 5, here is what I'm currently doing:

1. Disable the `cssCodeSplit` config option in Vite. This will put all emitted CSS in one file.
2. In your backend adapter, open up the generated `manifest.json` file (usually in public/vite/.vite/manifest.json).
3. In this file look for the `style.css` entry.
4. Add a link to that file in your <head>

Here's an example for Rails:
```rb
  def vite_global_style_tag
    if Rails.env.test?
      vite_folder = "vite-test"
    else
      vite_folder = "vite"
    end

    manifest_path = Rails.root.join("public", vite_folder, ".vite", "manifest.json")
    return "" unless File.exist?(manifest_path)
    manifest = JSON.parse(File.read(manifest_path))
    file = manifest["style.css"]["file"]
    stylesheet_link_tag("/#{vite_folder}/#{file}", media: "all")
  end
```

This file will contain all global and component CSS. This isn't optimal for large apps, but have to start somewhere.

Svelte 5 recently also introduced the `css: 'inject'` compiler option, but according to Rich Harris, this is only for toy projects that can't figure out how to use the manifest.

**Comment by pedroborges** [comment]
#1970 has been merged, and SSR should now work correctly with both Svelte 4 and 5. You can refer to the Svelte playgrounds as examples. Let me know if you run into any issues!

**Comment by buhrmi** [comment]
This shouldn't be closed as this is still a problem with Svelte 5. Or can you point me to where in the playground example you are rendering the component CSS during SSR?

**Comment by pedroborges** [comment]
@buhrmi If you're still experiencing this issue with Svelte 5, please feel free to reopen the PR. Additionally, providing a reproducible repository would help us investigate.

**Comment by buhrmi** [comment]
@pedroborges just add any CSS in a <style> tag to any Svelte component and you will see the style being applied AFTER the initial render.

I see that the Svelte 5 playground code has no component styles whatsoever, so I guess that's why you're not experiencing it.

Let me know if you still require a repo.

**Comment by buhrmi** [comment]
Also, the PR was only for Svelte 4. As I've stated [here](https://github.com/inertiajs/inertia/issues/1760#issuecomment-2181686362), we are still lacking a solution for this problem for Svelte 5.

**Comment by buhrmi** [comment]
Looks like 3 months ago they added the `css: 'inject'` compiler option in Svelte 5, which adds back the CSS. According to Rich Harris, this is only for toy projects. It *does* work, however. I'll just make a PR to the playground that adds the compiler option, even if Rich will call us a toy project for all of eternity.

**Comment by buhrmi** [comment]
okay I can confirm that the `css: 'inject'` compiler option prevents layout flashing. closing.
