### ISSUE TITLE
v-if causing "Unhandled error during execution of scheduler flush" after form.post

### ISSUE THREAD

**Issue by erikaraujo** [inertiajs/inertia#654]
### Versions:

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-vue3` version: 0.3.14
- `vue` version 3.0.11

### Describe the problem:

When posting a form that updates a prop that is being used in a `v-if` something goes wrong.

Getting a warning with:
> [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug.

Followed by an error:
>TypeError: can't access property "insertBefore", parent is null

### Steps to reproduce:

I'm using Laravel and Vue3.
Here's a component (Route/Index):
```vue
<template>
  <!-- here I have a layout component -->
    <form @submit.prevent="form.post(route('route.post'))">
      <button>Create thing</button>
    </form>
    <div v-if="someProp">
      {{ someProp }}
    </div>
   <!-- end of layout component -->
</template>
<script>
import { useForm } from '@inertiajs/inertia-vue3'
export default {
  props: {
    someProp: String
  }
  setup () {
    const form = useForm()
    return { form }
  },
}
</script>
```

Here's the laravel controller methods:
```php
public function index()
{
    return Inertia::render('Route/Index', [
        'someProp' => session()->get('propContent'),
    ]);
}

public function store()
{
    // do stuff
    $prop = 'Blabla';
    return redirect()->back()->with('propContent', $prop);
}
```

### Workaround

As a workaround I'm adding `{ preserveState: false }` to `form.post` and it works.

**Comment by dlquattro** [comment]
I'm having the same problem when using `v-for` with an empty list and then adding the first record (with a database and `useForm` helper). Once the first record is added I stop having this error, this only happens if my database table is empty and I add the first record in it.

The `preserveState: false` does work as a workaround, so I set it to `false` for the first record and then to `true`.

**Comment by freakzlike** [comment]
I got the same issue when i try to toggle a `div` with `v-if` without prop relation after `form.put`. Moving the logic with `v-if` to an own component also works without need to set `preserveState: false`.

I think this is the same problem as mentioned in #634

**Comment by hcancelik** [comment]
`preserveState: false` is causing a full component render which is not desired in my case. Is there any other solution for this? 

I'm trying to display the validation errors in v-for and after $inertia.post call but getting the `TypeError: can't access property "insertBefore", parent is null` error.

**Comment by alasdairgallacher** [comment]
I've got the same problem...

Using `preserveState: false` does workaround the problem. However, it prevents "repopulating" the form, which is not ideal.

**Comment by reinink** [comment]
Hey folks, this issue sounds similar to this one: #615

As noted in my comment on that issue, I was able to fix the issue by wrapping by entire page component in an extra `<div>`. I have a feeling this issue is related to fragments in Vue 3.

Give that a try and let me know?

**Comment by hcancelik** [comment]
@reinink I was also able to get it worked by moving the logic to another (sub) component as @freakzlike suggested.

**Comment by erikaraujo** [comment]
> 
> 
> Hey folks, this issue sounds similar to this one: #615
> 
> As noted in my comment on that issue, I was able to fix the issue by wrapping by entire page component in an extra `<div>`. I have a feeling this issue is related to fragments in Vue 3.
> 
> Give that a try and let me know?

Yup, this did it for me too. Thanks!

Unfortunately it adds unnecessary markup, but it's better than re-rendering the entire page.
I imagine this is more of a Vue 3 issue than Inertia, since you mentioned fragments possibly being the culprit?

**Comment by dlquattro** [comment]
> Hey folks, this issue sounds similar to this one: #615
> 
> As noted in my comment on that issue, I was able to fix the issue by wrapping by entire page component in an extra `<div>`. I have a feeling this issue is related to fragments in Vue 3.
> 
> Give that a try and let me know?

This worked for me too, thanks!

**Comment by alasdairgallacher** [comment]
I don't know if this is the same issue, but I have a feeling it's linked...

I have a Vue page which holds a child component for a login form.
On submit, I use `this.$inertia.post('/login', this.form)` (within the LoginForm component).
On the parent page my plan is to use `v-if="auth.user"` to show a payment button and then `v-else` to show the login form. (They need to be logged in to pay)

When I submit the login form, the parent is able to update `{{ auth.user }}`. It goes from displaying something like `{"user": null} to `{"user:"{id:1...`

However, I am unable to use `v-if="auth.user"`, it gives me the error `[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'parent.insertBefore')`.

I've even tried wrapping this div with another div, as mentioned by @reinink (which fixed my previous issue). However, this didn't work neither did trying `v-if="(auth) && auth.user"` 

I would really appreciate any help with this... Thanks

**Comment by alasdairgallacher** [comment]
> I don't know if this is the same issue, but I have a feeling it's linked...
> 
> I have a Vue page which holds a child component for a login form.
> On submit, I use `this.$inertia.post('/login', this.form)` (within the LoginForm component).
> On the parent page my plan is to use `v-if="auth.user"` to show a payment button and then `v-else` to show the login form. (They need to be logged in to pay).
> 
> When I submit the login form, the parent is able to update `{{ auth.user }}`. It goes from displaying something like `{"user": null}` to `{"user:"{id:1...`, which shows the prop is updating...
> 
> However, I am unable to use `v-if="auth.user"`, it gives me the error `[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'parent.insertBefore')`.
> 
> I've even tried wrapping this div with another div, as mentioned by @reinink (which fixed my previous issue). However, this didn't work neither did trying `v-if="(auth) && auth.user"`
> 
> I would really appreciate any help with this... Thanks

I fixed this by adding a wrapping div with `v-if="auth"`. Very odd situation, but I hope this helps someone else!

**Comment by reinink** [comment]
Folks, please try to update to the latest version of Vue 3. I think this is an issue with Vue 3, and I'm [getting reports](https://twitter.com/jeffrey_way/status/1391772547935576064) it's been corrected in newer releases.

**Comment by heychazza** [comment]
Sadly issue still applies to me.. #678

**Comment by dlquattro** [comment]
> Folks, please try to update to the latest version of Vue 3. I think this is an issue with Vue 3, and I'm [getting reports](https://twitter.com/jeffrey_way/status/1391772547935576064) it's been corrected in newer releases.

I upgraded as Jeffrey suggested (both with `v3.1.0-beta.2` and `v3.1.0-beta.3`) but I still get the same issue. For the moment I'm gonna stick with your solution (wrapping the component in a `<div>`).

**Comment by kishan93** [comment]
> As noted in my comment on that issue, I was able to fix the issue by wrapping by entire page component in an extra `<div>`. I have a feeling this issue is related to fragments in Vue 3.

Thank you so much @reinink . I spent 1 hour trying to figure out what was wrong. this fixed it for me.

I will update Vue version latter on.

**Comment by Talbourdet** [comment]
Thank you @reinink for this temporary solution

**Comment by seshac** [comment]
Instead, if v-if try with v-show

something like these
```
    <div v-show="someProp">
      {{ someProp }}
    </div>

```

**Comment by zeke0816** [comment]
I just had a similar issue using `form.put`, like @freakzlike. I don't think it had to do with `v-if` because I'm using `v-if` in another component and it's working fine, but in this case I'm using Laravel Jetstream's DialogModal component which I filled with a quick form to insert into the database and continue editing after a redirection. That's where I get the problem. The exact error I got is as follows:

`Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'parent.insertBefore')`

The insertion is executed successfully and everything works fine after a simple refresh, but the error is there and it doesn't redirect you automatically because of the error. (The controller function returns a RedirectResponse).

I was able to fix it using the workaround provided in this issue (`{ preserveState: false }`) but it's now also giving me the obvious deprecation warning. I'm hoping someone finds this information useful to hit on the definitive solution.

Versions (same as original post):

- `@inertiajs/inertia` version: 0.8.7
- `@inertiajs/inertia-vue3` version: 0.3.14
- `vue` version 3.0.11

**Comment by reinink** [comment]
@zeke0816 Try upgrading to the latest version of `@inertiajs/inertia`, `@inertiajs/inertia-vue3` and `vue`. Plus, also try wrapping your page component in a `<div>`, as I think this problem is related to fragments in Vue 3. Let me know if that helps.

**Comment by zeke0816** [comment]
@reinink I updated to the latest versions as of today and made sure the page component was wrapped in a `<div>`. However, although the error disappeared and the DialogModal now closes normally, the page does not react to the changes so the new row does not appear until the page is refreshed. I'll keep the latest versions as they're working fine, but I guess there is something else going on. The function in the controller returns `Redirect::route('some.route')`, but I guess it doesn't redirect that one time. All other forms work just fine. I do have a workaround, as I said before, so I suppose there is no real hurry for me but I'm willing to provide more details if needed to solve the issue.

**Comment by sando57** [comment]
@reinink I had this exact issue on a new install of Laravel / Jetstream / Inertia.

- NPM update (Vue 3.0.5 to 3.1.5 and inertia 0.9.1 to 0.9.4) fixed the error

**Comment by reinink** [comment]
Hey! Thanks so much for your interest in Inertia.js and for sharing this issue/suggestion.

In an attempt to get on top of the issues and pull requests on this project I am going through all the older issues and PRs and closing them, as there's a decent chance that they have since been resolved or are simply not relevant any longer. My hope is that with a "clean slate" me and the other project maintainers will be able to better keep on top of issues and PRs moving forward.

Of course there's a chance that this issue is still relevant, and if that's the case feel free to simply submit a new issue. The only thing I ask is that you please include a super minimal reproduction of the issue as a Git repo. This makes it much easier for us to reproduce things on our end and ultimately fix it.

Really not trying to be dismissive here, I just need to find a way to get this project back into a state that I am able to maintain it. Hope that makes sense! ❤️
