### ISSUE TITLE
Unable to install the packages

### ISSUE THREAD

**Issue by maxacarvalho** [inertiajs/inertia#805]
### Versions:

- `@inertiajs/inertia` version: latest
- `@inertiajs/inertia-vue3` version: latest

### Describe the problem:

I'm following the docs and I can't install the packages, see error below.

### Steps to reproduce:

Simply run `npm install @inertiajs/inertia @inertiajs/inertia-vue3`

### Error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @inertiajs/inertia@undefined
npm ERR! node_modules/@inertiajs/inertia
npm ERR!   @inertiajs/inertia@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @inertiajs/inertia@"^0.10.0" from @inertiajs/inertia-vue3@0.5.1
npm ERR! node_modules/@inertiajs/inertia-vue3
npm ERR!   @inertiajs/inertia-vue3@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by georgehanson** [comment]
Not 100% sure why - but I managed to solve the above by separating them into two separate install commands.

`npm i @inertiajs/inertia` followed by `npm i @inertiajs/inertia-vue3`

**Comment by reinink** [comment]
Yeah, sorry, we did some package publishing last night, and forgot to publish one version. Try again, it should work now. 👍

**Comment by maxacarvalho** [comment]
@reinink I'm still getting the same error more or less. I also tried `npm cache clean` to see if it would sort things out, no success.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @inertiajs/inertia@0.9.4
npm ERR! node_modules/@inertiajs/inertia
npm ERR!   peer @inertiajs/inertia@"^0.6.0 || ^0.7.0 || ^0.8.0 || ^0.9.0" from @inertiajs/progress@0.2.5
npm ERR!   node_modules/@inertiajs/progress
npm ERR!     @inertiajs/progress@"^0.2.5" from the root project
npm ERR!   @inertiajs/inertia@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @inertiajs/inertia-vue3@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @inertiajs/inertia@0.10.0
npm ERR! node_modules/@inertiajs/inertia
npm ERR!   peer @inertiajs/inertia@"^0.10.0" from @inertiajs/inertia-vue3@0.5.1
npm ERR!   node_modules/@inertiajs/inertia-vue3
npm ERR!     @inertiajs/inertia-vue3@"*" from the root project
```

**Comment by reinink** [comment]
Can you show me the versions set in your package.json file for the Inertia packages?

**Comment by maxacarvalho** [comment]
Hi @reinink, so, it's the `npm install @inertiajs/progress` that's broken.  
I deleted the `node_modules` and deleted the lock file, then removed the Inertia packages and started installing one by one again. It fails when I try to install the `@inertiajs/progress` package.

Here's my package versions:

```
...
    "@inertiajs/inertia": "^0.10.0",
    "@inertiajs/inertia-vue3": "^0.5.1",
...
```

**Comment by reinink** [comment]
Ugh, yeah, that makes sense. We need to update that library to support `0.10.0`. I'll try get that done within the next couple hours.

**Comment by reinink** [comment]
Okay this has been fixed and published: https://github.com/inertiajs/progress/commit/259f19ba5e573720f148b41589768d7b026bfe20

Update to `@inertiajs/progress@0.2.6`. 👍
