### ISSUE TITLE
Scroll not resetting on the body element

### ISSUE THREAD

**Issue by p4rz1val** [inertiajs/inertia#84]
### Description

`setScroll` is not resetting the scroll position on the body.

### Steps to reproduce:

1. Create two pages in an inertia project where you can scroll
2. Add an Inertia Link to go from page 2 to page 1
3. Go to page 2 and scroll
4. Go back to Page 1 using the Inertia Link 

```
setScroll(preserveScroll) {
    if (!preserveScroll) {
      document.querySelectorAll('body,[scroll-region]')
        .forEach(region => region.scrollTo(0, 0))
    }
  },
```
### Info
Go to an Inertia Page where you can scroll, in your console and try to reset the body scroll position manually using `document.querySelector('body').scrollTo(0, 0)`

In both cases it's not resetting the scroll position, you can however try to **select the html element instead of the body element** and it should work

**Comment by reinink** [comment]
Interesting. What browser are you using?

**Comment by p4rz1val** [comment]
Tried in Chrome 77.0.3865.90 and Firefox 69.0.1

The problem is related to the scrollTo function in javascript, here´s a fiddle showing the issue: https://jsfiddle.net/qL4m9o6x/2/

**Comment by smbdelse** [comment]
I had this issue in Chrome and indeed html element works where body is not

**Comment by danielstgt** [comment]
A PR that also selects the html element is available #87.

**Comment by reinink** [comment]
Fixed via #87.

**Comment by dajoeberlei** [comment]
+1 having the same issue.  

I have very basic <inertia-link :href="rote('booking.index')> links without any preserve-scroll attached to it and its not scrolling to top unfortunately. 

Is there a global configuration i am missing? Its happening to all of my links. The weird thing is it occurs on a project that im working on for a while and i didnt have the issue from the beginning i think (not sure though). But i cant recall changing anything global related to scrolling. (its a jetstream inertia-vue application)

**Comment by dajoeberlei** [comment]
I just found out that it scrolls back to top on chrome but not in firefox (98.0.1).

**Comment by vpuentem** [comment]
> +1 having the same issue.
> 
> I have very basic <inertia-link :href="rote('booking.index')> links without any preserve-scroll attached to it and its not scrolling to top unfortunately.
> 
> Is there a global configuration i am missing? Its happening to all of my links. The weird thing is it occurs on a project that im working on for a while and i didnt have the issue from the beginning i think (not sure though). But i cant recall changing anything global related to scrolling. (its a jetstream inertia-vue application)

Having the same issue, no _preverse-scroll_ property attached to the link but it is preserving scroll anyway

**Comment by fgd007** [comment]
I had the same issue. And I was swearing that I wasn't preserving the scroll position before. But then I recalled that I had added the property `scroll-behavior: smooth` on the html element. Removing that fixed it. Something to look into though.

**Comment by jeffreyvanhees** [comment]
> I had the same issue. And I was swearing that I wasn't preserving the scroll position before. But then I recalled that I had added the property `scroll-behavior: smooth` on the html element. Removing that fixed it. Something to look into though.

Thanks, that's the solution. It is not scrolling to top automatically when using the `.scroll-smooth`-class.

**Comment by MooseSaeed** [comment]
> I had the same issue. And I was swearing that I wasn't preserving the scroll position before. But then I recalled that I had added the property `scroll-behavior: smooth` on the html element. Removing that fixed it. Something to look into though.

Thank you! That helped

**Comment by raphaelbeckmann** [comment]
`scroll-behavior: smooth` is indeed responsible for this issue, at least on the current versions of Firefox (104) and Chrome (104).
The current version of Safari (15.6.1) however DOES scroll top with the smooth scroll behavior setting.

**Comment by raphaelbeckmann** [comment]
I just found a pull request fixing this issue. It seems like it's already merged.

https://github.com/inertiajs/inertia/pull/1099

**Comment by MooseSaeed** [comment]
> I just found a pull request fixing this issue. It seems like it's already merged.
> 
> #1099

For some reason, I'm still having the same issue on the latest Inertia Laravel version. I hope @reinink can help

**Comment by raphaelbeckmann** [comment]
> For some reason, I'm still having the same issue on the latest Inertia Laravel version. I hope @reinink can help

Yes, me too. Unfortunately, there hasn't been released a new version with this fix.

**Comment by Malikmal** [comment]
Hello, is there any alternative solution ?. 
I've try using global CSS html `{scroll-behavior:unset}` to fixing it resetting scroll when redirect page
and in my 1 page that need smooth scroll I import CSS file that contains `html{scroll-behavior:smooth}` to keep worked for anchor smooth scrolling. but it doesn't work properly

**Comment by samharvey44** [comment]
Issue still exists.

**Comment by alejandrotrevi** [comment]
This issue was solved a while ago. You should consider opening a new one to get better support.

**Comment by raphaelbeckmann** [comment]
@samharvey44 @alejandrotrevi I can confirm it's not solved even with `@inertiajs/inertia@0.11.1`

**Comment by vermataruna** [comment]
Agreed with @raphaelbeckmann
